# vim ft=yaml
# travis-ci.org definition for skfuzzy build
#
# Check changes to this file on http://lint.travis-ci.org/

language: python

python:
    - 2.6

matrix:
    include:
        - python: 2.7
          env:
            - PYTHON=python
            - PYVER=2.x
        - python: 3.2
          env:
            - PYTHON=python3
            - PYVER=3.x
    exclude:
        - python: 2.6

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update
    - sudo apt-get install $PYTHON-numpy
    - wget https://raw.githubusercontent.com/numpy/numpy/master/numpy/_import_tools.py -O /home/travis/virtualenv/python3.2_with_system_site_packages/lib/python3.2/site-packages/numpy/_import_tools.py
    - sudo apt-get install $PYTHON-scipy
    - if [[ $PYVER == '2.x' ]]; then
    -   sudo apt-get install $PYTHON-matplotlib
    - fi
    - if [[ $PYVER == '3.x' ]]; then
    -   sudo apt-get install $PYTHON-setuptools
    -   pip install --use-mirrors matplotlib
    - fi
    # - pip install --use-mirrors cython  # If skfuzzy ever uses Cython
    - pip install --use-mirrors flake8
    - pip install --use-mirrors nose-cov
    - pip install --use-mirrors coveralls

install:
    - sudo $PYTHON setup.py install

script:
    # Run tests
    - nosetests --exe -v --with-cov --cov skfuzzy --cov-config .coveragerc skfuzzy

after_success:
    - if [[ $PYVER == '3.x' ]]; then
    -   coveralls
    - fi
